services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ademiro
      - MINIO_ROOT_PASSWORD=a1b@C3d4e5
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  postgres:
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prod
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=prod-pg
      - S3_ACCESS_KEY_ID=ademiro
      - S3_SECRET_ACCESS_KEY=a1b@C3d4e5
      - PG_LOG_LEVEL=debug
    ports:
      - 3456:3456
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-state:/var/lib/pg
    depends_on:
      - minio

volumes:
  minio-data:
  pg-data:
  pg-state:
